spring:
  application:
    name: demo
  
  datasource:
    jndi-name: java:/jdbc/todoDS
    # url: jdbc:postgresql://localhost:5432/appdb
    # username: appuser
    # password: apppass
    # driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true